obj-m :=hello.o
obj-m +=ex02.o
obj-m +=ex03.o

obj-m :=ex0203.o
ex0203-objs :=ex02.o ex03.o

obj-m :=hello.o
obj-m +=ex04.o

obj-m :=ex05_exporting.o
obj-m +=ex05_using.o

obj-m :=ex06_parameters.o


obj-m :=ex07.o

